=== qazuor/web-app-scaffold/packages/generator/templates/package.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "PackageConfig",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "JSON Schema version or schema URL"
        },
        "name": {
            "type": "string",
            "description": "Package name as it appears in package.json"
        },
        "displayName": {
            "type": "string",
            "description": "Display name for the package in the selection prompt"
        },
        "description": {
            "type": "string",
            "description": "Short description of the package"
        },
        "version": {
            "type": "string",
            "description": "Version of the package to install",
            "pattern": "^(?:\\^|~)?\\d+\\.\\d+\\.\\d+(?:-[\\w.-]+)?(?:\\+[\\w.-]+)?$"
        },
        "supportedFrameworks": {
            "type": "array",
            "items": { "type": "string" },
            "description": "Frameworks this package is compatible with"
        },
        "isDev": {
            "type": "boolean",
            "description": "Whether this is a dev dependency"
        },
        "dependencies": {
            "type": "array",
            "items": { "$ref": "#/definitions/PackageDependency" },
            "description": "Additional dependencies that should be installed with this package"
        },
        "devDependencies": {
            "type": "array",
            "items": { "$ref": "#/definitions/PackageDependency" },
            "description": "Additional dev dependencies that should be installed with this package"
        },
        "scripts": {
            "type": "array",
            "items": { "$ref": "#/definitions/PackageScript" },
            "description": "Additional scripts to be added to app package.json"
        },
        "envVars": {
            "type": "array",
            "items": { "$ref": "#/definitions/PackageEnvVar" },
            "description": "Additional env vars to be added to app"
        },
        "isUILibrary": {
            "type": "boolean",
            "description": "Whether this package is a UI library"
        },
        "isIconLibrary": {
            "type": "boolean",
            "description": "Whether this package is an icon library"
        },
        "canBeSharedPackage": {
            "type": "boolean",
            "description": "Whether this package can be installed as a shared package"
        },
        "sharedPackageDefaultName": {
            "type": "string",
            "description": "Default name for the shared package"
        },
        "sharedPackageDefaultDescription": {
            "type": "string",
            "description": "Default description for the shared package"
        },
        "extraOptionsPrompts": {
            "type": "array",
            "description": "Prompts configs for additional options for this package",
            "items": {
                "$ref": "#/definitions/ExtraOptionPrompt"
            }
        }
    },
    "required": ["name", "displayName", "description", "version"],
    "additionalProperties": false,
    "definitions": {
        "PackageDependency": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "pattern": "^(@[a-z0-9-~][a-z0-9-._~]*\\/)?[a-z0-9-~][a-z0-9-._~]*$",
                    "description": "NPM package name (valid format)"
                },
                "version": {
                    "type": "string",
                    "pattern": "^(?:\\^|~)?\\d+\\.\\d+\\.\\d+(?:-[\\w.-]+)?(?:\\+[\\w.-]+)?$",
                    "description": "Semver version (valid format)"
                },
                "addInShared": {
                    "type": "boolean",
                    "description": "Whether this dependency should be installed in the shared package"
                },
                "addInApp": {
                    "type": "boolean",
                    "description": "Whether this dependency should be installed in the app package"
                }
            },
            "required": ["name", "version"],
            "additionalProperties": false
        },
        "PackageScript": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "command": { "type": "string" },
                "addInShared": {
                    "type": "boolean",
                    "description": "Whether to add this script in shared package.json"
                },
                "addInApp": {
                    "type": "boolean",
                    "description": "Whether to add this script in app package.json"
                }
            },
            "required": ["name", "command"],
            "additionalProperties": false
        },
        "PackageEnvVar": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "pattern": "^[A-Z0-9_]+$"
                },
                "value": {
                    "oneOf": [
                        { "type": "boolean" },
                        { "type": "string" },
                        {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        { "type": "number" },
                        {
                            "type": "array",
                            "items": { "type": "number" }
                        }
                    ]
                },
                "addInShared": {
                    "type": "boolean",
                    "description": "Whether to add this script in shared package.json"
                },
                "addInApp": {
                    "type": "boolean",
                    "description": "Whether to add this script in app package.json"
                }
            },
            "required": ["name", "value"],
            "additionalProperties": false
        },
        "ExtraOptionPrompt": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["input", "confirm", "list", "checkbox"]
                },
                "name": { "type": "string" },
                "message": { "type": "string" },
                "choices": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": { "type": "string" },
                            "value": { "type": "string" }
                        },
                        "required": ["name", "value"],
                        "additionalProperties": false
                    }
                },
                "default": {
                    "oneOf": [
                        { "type": "boolean" },
                        { "type": "string" },
                        {
                            "type": "array",
                            "items": { "type": "string" }
                        },
                        { "type": "number" },
                        {
                            "type": "array",
                            "items": { "type": "number" }
                        }
                    ]
                }
            },
            "required": ["type", "name", "message"],
            "additionalProperties": false
        }
    }
}

=== qazuor/web-app-scaffold/packages/generator/templates/packages/example-package/config.json
{
    "$schema": "../../package.schema.json",
    "name": "example-package",
    "displayName": "Example Package",
    "description": "Example Package description",
    "version": "^1.0.0",
    "dependencies": [
        {
            "name": "example-dependency-from-config-file1",
            "version": "^1.0.0"
        }
    ],
    "devDependencies": [
        {
            "name": "example-dev-dependency-from-config-file",
            "version": "^1.0.0"
        }
    ],
    "scripts": [{ "name": "example-script-from-config-file1", "command": "tsc --noEmit" }],
    "envVars": [{ "name": "EXAMPLE_ENV_VAR_FROM_CONFIG_FILE_1", "value": "pepe" }],
    "isUILibrary": false,
    "isIconLibrary": false,
    "canBeSharedPackage": true,
    "sharedPackageDefaultName": "example",
    "sharedPackageDefaultDescription": "example shared package description",
    "extraOptionsPrompts": [
        {
            "type": "checkbox",
            "name": "authentication-strategies",
            "message": "Which authentication strategy would you like to use?",
            "choices": [
                {
                    "name": "Email & Password - Traditional authentication",
                    "value": "email-password"
                },
                { "name": "Google - Social sign-in with Google", "value": "google" },
                { "name": "Facebook - Social sign-in with Facebook", "value": "facebook" }
            ],
            "default": "email-password"
        }
    ]
}
